const dialogsConsts = {
  DIALOGS_FETCH_REQUEST: 'DIALOGS_FETCH_REQUEST',
  DIALOGS_FETCH_SUCCESS: 'DIALOGS_FETCH_SUCCESS',
  DIALOGS_FETCH_FAILURE: 'DIALOGS_FETCH_FAILURE',
};
export default dialogsConsts;
